import env from '../utils/env';

export const TOKEN = env.get('bot_token', true);
export const BOT_ID = env.get('bot_id', true);
export const REST_PORT = env.get('rest_port', true);
export const REST_URL = env.get('rest_url', true);
export const GATEWAY_PORT = env.get('gateway_port', true);
export const GATEWAY_URL = env.get('gateway_url', true);
export const SHARD_SERVER_PORT = env.get('shard_server_port', true);
export const SHARD_SERVER_URL = env.get('shard_server_url', true);
export const EVENT_SERVER_URL = env.get('event_server_url', true);
export const EVENT_SERVER_PORT = env.get('event_server_port', true);
export const XATA_API_KEY = env.get('xata_api_key', true);
export const XATA_BRANCH = env.get('xata_branch', true);
export const REDIS_PASSWORD = env.get('redis_password', true);
export const REDIS_HOST = env.get('redis_host', true);
export const REDIS_PORT = env.get('redis_port', true);
export const INFLUX_ENABLE = env.get('influx_enable', true);
export const INFLUX_URL = env.get('influx_url');
export const INFLUX_TOKEN = env.get('influx_token');
export const INFLUX_ORG = env.get('influx_org');
export const INFLUX_BUCKET = env.get('influx_bucket');
export const PERSPECTIVE_API_KEY = env.get('perspective_api_key', true);
